In [15]:
#Create a 4x4 array of random integers between 1-50, find the maximum value in each row
import numpy as np

array=np.random.randint(0,51,size=(4,4))
print("Array=",array)
max_vals=np.max(array,axis=1)
print("\n\n\n")
print(max_vals.shape)
print(max_vals)

Array= [[45 27 15 50]
 [ 7 39 20 39]
 [36  8 15 21]
 [45  4 31 32]]




(4,)
[50 39 36 45]


In [19]:
#Create two 1D arrays of size 8, compute their sum and find elements greater than 10
import numpy as np

array1=np.random.randint(0,101,size=(1,8))
array2=np.random.randint(0,11,size=(1,8))
print("array1",array1)
print("array2",array2)
sum_array=array1+array2
print("sum   ",sum_array)
print(">10 elements")
high_array=sum_array[sum_array>10]
print(high_array)

array1 [[43 77 65 18 44 65 45  4]]
array2 [[5 0 2 3 9 4 9 3]]
sum    [[48 77 67 21 53 69 54  7]]
>10 elements
[48 77 67 21 53 69 54]


In [4]:
# Create a DataFrame with columns (student, score, grade) for 6 students, filter students with score > 75
import pandas as pd

df=pd.DataFrame({
    'student':['Ali', 'Ayna', 'Arslan', 'Mira', 'Begench'],
    'score':[88, 92, 80, 72, 68],
    'grade':['b','a','b','c','d']
})

high_scores=df[df['score']>75]
print("Students >75 score")
print(high_scores)


Students >75 score
  student  score grade
0     Ali     88     b
1    Ayna     92     a
2  Arslan     80     b


In [11]:
#4. Create a Series of 10 temperatures, calculate mean and find days above average
import pandas as pd
import numpy as np

temp=np.array([32,12,32,12,43,11,23,21,15,16])
days=np.array([1,2,3,4,5,6,7,8,9,10])

df=pd.DataFrame({
        'temperature': temp,
        'days' : days
})

average_temp=np.mean(temp)

high_temp=df[df["temperature"]>average_temp]
print("Higher Temperatures than Average")
print(high_temp)

Higher Temperatures than Average
   temperature  days
0           32     1
2           32     3
4           43     5
6           23     7


In [21]:
# Create a 6x6 matrix, extract the diagonal, and replace it with zeros
import numpy as np

array=np.random.randint(0,11,size=(6,6))
print(array)

diag=np.diag(array)

print("\n",diag)

np.fill_diagonal(array,0)
print("\n",array)

[[ 6  4  9  6  6  2]
 [ 7 10  4 10  1  1]
 [ 7  7  5  6  3  6]
 [ 7  7  4  7  6  1]
 [ 1  0  3  2  0  5]
 [ 8 10  4  7  3  1]]

 [ 6 10  5  7  0  1]

 [[ 0  4  9  6  6  2]
 [ 7  0  4 10  1  1]
 [ 7  7  0  6  3  6]
 [ 7  7  4  0  6  1]
 [ 1  0  3  2  0  5]
 [ 8 10  4  7  3  0]]


In [19]:
#Generate a 3D array of shape (3, 4, 5) and compute the sum along each axis
import numpy as np

arr=np.random.randint(0, 11,size=(3,4,5))
print("Array\n",arr,"\n")

sum_axis0=np.sum(arr,axis=0)
sum_axis1=np.sum(arr,axis=1)
sum_axis2=np.sum(arr,axis=2)

print("\nSum of axis=0 \n",sum_axis0)
print("\nSum of axis=1 \n",sum_axis1)
print("\nSum of axis=2 \n",sum_axis2)

Array
 [[[ 3  2 10  1  8]
  [ 8  2  6  3  1]
  [ 4  6  3  8 10]
  [ 1  4  2  8  4]]

 [[ 5  1 10  0  9]
  [10  3  3  1 10]
  [ 9  1  2 10  5]
  [ 1  5  2  1  8]]

 [[ 7  4  5  8 10]
  [ 6  1  8  3  5]
  [ 2  0  8  4  9]
  [ 9  3  8  6  9]]] 


Sum of axis=0 
 [[15  7 25  9 27]
 [24  6 17  7 16]
 [15  7 13 22 24]
 [11 12 12 15 21]]

Sum of axis=1 
 [[16 14 21 20 23]
 [25 10 17 12 32]
 [24  8 29 21 33]]

Sum of axis=2 
 [[24 20 31 19]
 [25 27 27 17]
 [34 23 23 35]]


In [3]:
#Create a DataFrame with sales data (month, product, revenue), group by product and find total revenue
import numpy as np
import pandas as pd

month=np.array(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
product=np.array(['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'])
revenue=np.random.randint(100, 1000, size=12)

df=pd.DataFrame({'Month': month, 'Product': product, 'Revenue': revenue})

total_revenue=df.groupby('Product')['Revenue'].sum()
print("Total Revenue by Product")
print(total_revenue)

Total Revenue by Product
Product
A    1874
B    1744
C    2267
Name: Revenue, dtype: int32
