In [3]:
import pandas as pd
import numpy as np

In [4]:
array=np.random.randint(0, 51,size=(5,5))
print("Array:")
print(array)

Array:
[[28 15 22 43 26]
 [44 48 43 38  0]
 [28 14 38 38 46]
 [11 33 17 10 29]
 [45 44 26 46 43]]


In [9]:
#her setirin ortacasyny tapmak
means=array.mean(axis=0)
print("Avearges",means)

Avearges [31.2 30.8 29.2 35.  28.8]


In [ ]:
df=pd.DataFrame(means,columns=['mean